//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_ForceMode2DWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.ForceMode2D));
		L.RegVar("Force", get_Force, null);
		L.RegVar("Impulse", get_Impulse, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.ForceMode2D>.Check = CheckType;
		StackTraits<UnityEngine.ForceMode2D>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.ForceMode2D arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.ForceMode2D), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Force(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode2D.Force);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Impulse(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.ForceMode2D.Impulse);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.ForceMode2D o = (UnityEngine.ForceMode2D)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

